name: Build Bramble Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display system info
        run: |
          uname -a
          lscpu
          df -h
