name: Build Bramble Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git bc bison flex \
            build-essential \
            libssl-dev \
            libelf-dev \
            libncurses-dev \
            python3

      - name: Clone Android 14 kernel
        run: |
          git clone \
            --depth=1 \
            -b android-msm-redbull-4.19-android14-qpr3 \
            https://android.googlesource.com/kernel/msm \
            kernel

      - name: Verify source
        run: |
          cd kernel
          pwd
          ls
          ls arch/arm64/configs | grep bramble
